// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package nexmotextmessage.actions;

import com.nexmo.messaging.sdk.NexmoSmsClient;
import com.nexmo.messaging.sdk.NexmoSmsClientSSL;
import com.nexmo.messaging.sdk.SmsSubmissionResult;
import com.nexmo.messaging.sdk.messages.TextMessage;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * 
 */
public class SendText extends CustomJavaAction<String>
{
	private String APIKey;
	private String APISecret;
	private String FromText;
	private String PhoneNr;
	private String Text;

	public SendText(IContext context, String APIKey, String APISecret, String FromText, String PhoneNr, String Text)
	{
		super(context);
		this.APIKey = APIKey;
		this.APISecret = APISecret;
		this.FromText = FromText;
		this.PhoneNr = PhoneNr;
		this.Text = Text;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE

		        // Create a client for submitting to Nexmo

		        NexmoSmsClient client = null;
		        try {
		            client = new NexmoSmsClientSSL(APIKey, APISecret);
		        } catch (Exception e) {
		            System.err.println("Failed to instanciate a Nexmo Client");
		            e.printStackTrace();
		            throw new RuntimeException("Failed to instanciate a Nexmo Client");
		        }

		        // Create a Text SMS Message request object ...

		        TextMessage message = new TextMessage(FromText, PhoneNr, Text);

		        // Use the Nexmo client to submit the Text Message ...

		        SmsSubmissionResult[] results = null;
		        try {
		            results = client.submitMessage(message);
		        } catch (Exception e) {
		            System.err.println("Failed to communicate with the Nexmo Client");
		            e.printStackTrace();
		            throw new RuntimeException("Failed to communicate with the Nexmo Client");
		        }
		        
		        String result = "";

		        // Evaluate the results of the submission attempt ...
		        System.out.println("... Message submitted in [ " + results.length + " ] parts");
		        for (int i=0;i<results.length;i++) {
		        	result += "--------- part [ " + (i + 1) + " ] ------------" ;
		        	result += "Status [ " + results[i].getStatus() + " ] ...";
		            if (results[i].getStatus() == SmsSubmissionResult.STATUS_OK)
		            	result +="SUCCESS";
		            else if (results[i].getTemporaryError())
		            	result += "TEMPORARY FAILURE - PLEASE RETRY";
		            else
		            	result +="SUBMISSION FAILED!";
		            result +="Message-Id [ " + results[i].getMessageId() + " ] ...";
		            result +="Error-Text [ " + results[i].getErrorText() + " ] ...";

		            if (results[i].getMessagePrice() != null)
		            	result +="Message-Price [ " + results[i].getMessagePrice() + " ] ...";
		            if (results[i].getRemainingBalance() != null)
		            	result +="Remaining-Balance [ " + results[i].getRemainingBalance() + " ] ...";
		        }
		        return result;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SendText";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
